# Set the base image to Ubuntu
FROM continuumio/miniconda3

# File Author / Maintainer
MAINTAINER Thomas Schmelzer "thomas.schmelzer@gmail.com"

RUN conda install -q -y pandas flask nose

RUN pip install waitress

ADD . /pymonitor

WORKDIR /pymonitor


